name: Test

on: 
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-elixir@v1
      with:
          otp-version: '22.2'
          elixir-version: '1.9.4'
    
    - run: mix deps.get
    - run: mix test
