name: Test

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-elixir@v1
      with:
          otp-version: '23.3'
          elixir-version: '1.13.4'
    
    - run: mix deps.get
    - run: mix test
